package main

import (
	"time"
)

type Asset struct {
	Id        int    // auto generated by orm
	Ticker    string `pg:",unique"`
	Price     float64
	Qty       float32
	CreatedAt time.Time `pg:"default:now()" json:"created_at"`
	UpdatedAt time.Time `pg:"default:now()" json:"updated_at"`
}
